version: '3.8'

services:
  mysqlserver:
    container_name: 'jogoteca'
    image: 'mysql:8.0.28'
    restart: 'always'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'jogoteca'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    volumes:
      - './mysqldb:/var/lib/mysql'